select*from customers_analysis;

--Q1. What us the total revenue generated by male vs.female customers?
select gender, SUM(purchase_amount) as revenue
from customers_analysis
group by gender;

--Q2. Which customers used a discount but still spent more than average purchase amount?
select customer_id, purchase_amount
from customers_analysis
where discount_applied = 'yes' and purchase_amount >=(select AVG(purchase_amount) from customers_analysis);

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric), 2) as "Average product Rating"
from customers_analysis
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express shipping.
select shipping_type,
ROUND(AVG(purchase_amount), 2)
from customers_analysis
where shipping_type in ('Standard', 'Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribes.
select subscription_status,
	count(customer_id) as total_customers,
	round(avg(purchase_amount),2) as avg_spend,
	round(sum(purchase_amount),2) as total_revenue
from customers_analysis
group by subscription_status
order by total_revenue, avg_spend Desc;